[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "hydra-python-grpc"
version = "0.1.0"
description = "A project using gRPC generated stubs"
requires-python = ">=3.12"
dependencies = [
    "grpcio>=1.59.0",
    "grpcio-tools>=1.59.0",
    "protobuf>=4.24.0",
]
