name: Cross-Repository Dispatch

on:
  push:
    branches:
      - main  # or any branch you want to monitor

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in other repository
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/hydra-council/grpc-stubs/dispatches \
          -d '{"event_type": "generate_grpc", "client_payload": {"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}}'
